version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./vars.env
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./vars.env
